### PR TITLE
PeakShapes Resources

### PR DESCRIPTION
**Pull request by robinsonianr**

### CODE REVIEW

**Comment by bowring** [comment]
good start

**Comment by bowring** [comment]
@robinsonianr - good progress
1) the choose file button should be a choose folder button that causes the list to be populated - the list should be empty initially
2) then the file can be chosen from the the list - just clicking it will cause the graph to show

**Comment by bowring** [comment]
it needs to work with this folder (do not include it in Tripoli github) : 
https://drive.google.com/drive/folders/1IgpEAoZg73TblSDEWFI507AUuGX6sb44 

once this is working, we have more processing to do

**Comment by robinsonianr** [comment]
This works with the folder from google drive and sorts them accordingly

**Comment by bowring** [comment]
@robinsonianr - great job
next: 
1) read discussion about peak shapes : https://github.com/CIRDLES/Tripoli/discussions/44
2) while processing / sorting contents of peakcentre folder, create lists (or ArrayList<File>) that segregate the files according to their names so that all of files with name containing (for example) "-86Sr-Ax-" are grouped together.  This has to be robust enough to handle any element not just the ones we have here (86Sr, 87Sr, 88Sr), but you can rely on the shape of the name - the element name will start at the same place in all names (not count of characters since run3 might become run10).  Then, within each list, sort them by the last sub-string such as "S1B1C1".  This corresponds to time, but we don't want to depend on time stamps.  You will have to use the IntuitiveSringComparator class from: https://github.com/CIRDLES/Squid/blob/master/squidCore/src/main/java/org/cirdles/squid/utilities/IntuitiveStringComparator.java to guarantee that "B10" sorts after "B1".
3) provide the user with a list of these lists by presenting "86Sr-Ax", etc.  When the user chooses one of these list items, 
provide a lineplot in the right hand window ("Done", etc.) of the peak width = distance between two red dots on beam shape plot of each file in the list vs time: the xData will simply be 1,2,3,4,...#of files and the yData will be the values of the peak width for each of the files in their sorted order - plot a nice dot for each value.  Use the LinePlotBuilder.  Create a new "PeakCentresPlot" to render it.
4) have fun.  I am merging my latest work in a few minutes.
5) questions?

**Comment by bowring** [comment]
@robinsonianr - use the flag on line 51 of DataModelDriverExperiment to save time getting to visualizations

**Comment by bowring** [comment]
I updated branch from here so I can test it locally.

**Comment by bowring** [comment]
be sure the groups are:
86Sr-Ax
87Sr-Ax
88Sr-Ax

**Comment by robinsonianr** [comment]
I meant to print out the result but yes those groups are created and the files are sorted within them

**Comment by robinsonianr** [comment]
This should be robust enough to handle all the files assuming the files follow the same format that is present in the google drive PeakCentres even if run3 changes to run10.  Also, the files are sorted with the IntuitiveStringComparator.

**Comment by bowring** [comment]
be sure to comment out the line 38 in **IntuitiveStringComparator** as it is specific to Squid - I will show you how to generate for Tripoli
```java
private static final long serialVersionUID = 7971843528648376464L;
```
good progress

**Comment by bowring** [comment]
great job otherwise.  the middle collection seems to take quite a while to render - are you saving the builders?

**Comment by robinsonianr** [comment]
I and going to start saving the builders now. Also, not sure why one collections takes a while to render as well. For me it is the last one that take time to render.

**Comment by robinsonianr** [comment]
I determined that the 88Sr-Ax-S3B7C1 file goes through all iterations in the non-negative linear solver, which causes the collection to take a while to render the plot.

**Comment by bowring** [comment]
looking good
1) per Codacy - add "Util" to make FileHandlerUtil class name
2) deal with empty else noted by Codacy
3) display group names in sorted order
4) list file names in right panel when choosing a group

we will do a walkthrough today

**Comment by bowring** [comment]
@robinsonianr - look at revised PeakShapePlotsController (attached) for our discussion:
[PeakShapePlotsController.java.zip](https://github.com/CIRDLES/Tripoli/files/9375039/PeakShapePlotsController.java.zip)

**Comment by bowring** [comment]
@robinsonianr - looking good.  consider merging the two buttons

**Comment by bowring** [comment]
1) check peak widths ... the plot of widths does not seem to show the same values as the widths plotted above

**Comment by bowring** [comment]
study/borrow/etc mouse interactions in: 
https://github.com/CIRDLES/Squid/blob/master/squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/squid/WeightedMeanPlot.java

**Comment by bowring** [comment]
good start - be sure to use "MouseInHouse" to change mouse pointer
convert mouse position to index for use with looking up file
see you wed

**Comment by bowring** [comment]
thanks

**Comment by bowring** [comment]
looking good
be sure to restore the list of files on the right and allow single click on them as well ... try to highlight the chosen file if the red dot is clicked and place a slightly larger circle (oval) around the selected red dot in both cases

also, consider padding yMax so top red dot is not touching border - this will help with mouse position detection

**Comment by bowring** [comment]
getting there!
1) make list of files respond to single click
2) change button label to "Open Peak Centres Folder"
3) I think this makes a cleaner red dot at line 104 of PeakCentresLinePlot:
```java
g2d.fillOval(mapX(xAxisData[i]) - 4, mapY(yAxisData[i]) - 4, 8, 8);
```

4) try this for emphasizing the chosen file:
```java
g2d.setLineWidth(1.0);
            g2d.strokeOval(mapX(xAxisData[i]) - 6, mapY(yAxisData[i]) - 6, 12, 12);
```

5) in the case of only 1 file, just plot a red dot in the middle or show text "Only one file"

**Comment by bowring** [comment]
@robinsonianr - looking good!

one more refinement - when user clicks file name, the corresponding red dot should also be marked.

**Comment by bowring** [comment]
@robinsonianr - great!  I will merge shortly

**Pull request merged**
