### PR TITLE
Peak Refining and Doc

### PR DESCRIPTION
**Pull request by robinsonianr**

### CODE REVIEW

**Comment by bowring** [comment]
getting an error:
java.lang.NumberFormatException: For input string: "Timestamp"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:651)
	at org.cirdles.tripoli.sessions.analysis.massSpectrometerModels.dataSourceProcessors.PeakShapeProcessor_OPPhoenix.prepareInputDataModelFromFile(PeakShapeProcessor_OPPhoenix.java:69)

**Comment by bowring** [comment]
good opportunity to write some tests for this

**Comment by bowring** [comment]
good progress
note:
1) on **first** use of demo2, the auto-selection of the first file does not produce peak shape plots
2) when plotting ticsY, change line 130 to (float) mapX(minX) - textWidth - 5f,

**Comment by robinsonianr** [comment]
I believe the auto-selection was not working on the first use because peak service would not complete the task. I changed it not to use the service and it worked.

**Pull request merged**
