### PR TITLE
Update Delx Adapt

### PR DESCRIPTION
**Pull request by RoyalBoggs**
not outputting correct size matrix to delx adapt

### CODE REVIEW

**Comment by bowring** [comment]
@RoyalBoggs - did you solve the problem of single value in delxadapt?

**Comment by RoyalBoggs** [comment]
@bowring I believe you are referring to the delx_adapt_slice, I was able to confirm executing the matlab code in the command window that delx_adapt(:,mod(m,datsav)+1) returns a 1 x 20 column slice out of the delx_adapt matrix which is what is currently implemented, the finished current code however has a incorrect looking signal noise histogram which I believe stems from a bug in updateMSv2() which I'm currently investigating

**Comment by RoyalBoggs** [comment]
@bowring signal noise histogram returned to normal after changing adaptive flag counter to 10000 from 100 where I had it for testing, with it so low it breaks some of the logic for operation noise case in DataModellerOutputRecord updateMSv2 leading to signal noise not being adjusted, not sure that is bug or feature. Leads me to believe should stop working on delx adapt until algorithm for turning it on is set. That aside the multivariate normal distribution section of delx adapt I believe to be correct.

**Comment by bowring** [comment]
@RoyalBoggs - I set adaptiveflag at counter >= 1000 with max count of 2000 and got good results.

**Comment by bowring** [comment]
@RoyalBoggs - great work!

**Comment by bowring** [comment]
@RoyalBoggs - followup - chatted with @noahmclean and showed him results - there is some misbehavior but it is related to some coded in assumptions ... these will get fine-tuned with @sbordyak .

**Pull request merged**
