### PR TITLE
Adjusted allBlockInterpolations

### PR DESCRIPTION
**Pull request by RoyalBoggs**
Not completed

### CODE REVIEW

**Comment by bowring** [comment]
@RoyalBoggs - what is status of this PR?

**Comment by RoyalBoggs** [comment]
Still testing if data is correct but current iteration gives an "runs"

**Comment by RoyalBoggs** [comment]
Would recommend @bowring you review logic before merging the request, but I believe should be correct, method is a bit rough could be cleaned up a little in terms of parameters

**Comment by bowring** [comment]
@RoyalBoggs - this is good.  I am going to extract and modify to use with the new block processor and not change the method in its current location that will eventually be eliminated.

**Pull request merged**
