### PR TITLE
Ojalgo

### PR DESCRIPTION
**Pull request by RoyalBoggs**
Conversion from Jama library to Ojalgo for matrix multiplication

### CODE REVIEW

**Comment by bowring** [comment]
getting there!  now down to < 0.5 sec;

Elapsed time = 0.487 seconds for 1000 realizations of total = 47000
Intervals: in microseconds, each from prev or zero time till new interval Interval1 211 Interval2 217 Interval3 13 Interval4 96 Interval5 27


see what it will take to to serialize the MatrixStore in EnsembleRecord - this is a lead: http://javadox.com/org.ujmp/ujmp-ojalgo/0.3.0/serialized-form.html

**Comment by bowring** [comment]
speed is improving well:
%%%%%%%%%%%%%%%%%%%%%%% Tripoli in Java test %%%%%%%%%%%%%%%%%%%%%%%
Elapsed time = 0.423 seconds for 1000 realizations of total = 50000
Error function = 2978.623
Change Log Ratio: 149.0 of 150.0 accepted (97.966% total)
Change Intensity: 326.0 of 522.0 accepted (66.735% total)
Change DF Gain: 57.0 of 74.0 accepted (77.148% total)
Change Baseline: 23.0 of 82.0 accepted (35.326% total)
Noise: 27.0 of 172.0 accepted (19.020% total)
Intervals: in microseconds, each from prev or zero time till new interval Interval1 95 Interval2 170 Interval3 11 Interval4 94 Interval5 18

**Comment by bowring** [comment]
I am merging another PR from myself first - did some refactoring and tweaking as I found a bug in the logic.  

Once you fix the conflicts, I am willing to merge this.

looking faster!
%%%%%%%%%%%%%%%%%%%%%%% Tripoli in Java test %%%%%%%%%%%%%%%%%%%%%%%
Elapsed time = 0.391 seconds for 1000 realizations of total = 50000
Error function = 2972.754
Change Log Ratio: 160.0 of 163.0 accepted (98.014% total)
Change Intensity: 362.0 of 518.0 accepted (66.867% total)
Change DF Gain: 70.0 of 84.0 accepted (77.615% total)
Change Baseline: 24.0 of 64.0 accepted (34.393% total)
Noise: 41.0 of 171.0 accepted (19.331% total)
Intervals: in microseconds, each from prev or zero time till new interval Interval1 74 Interval2 172 Interval3 12 Interval4 81 Interval5 21

**Comment by RoyalBoggs** [comment]
Currently broken wait for next commit

**Comment by bowring** [comment]
@RoyalBoggs - good work!  I am merging and then doing a pull request for my additional work including a cleanup of the driverExperiement ... stand by.  Then do another pass and make sure we have all the speedups we can get - see my intervals below:

%%%%%%%%%%%%%%%%%%%%%%% Tripoli in Java test %%%%%%%%%%%%%%%%%%%%%%%
Elapsed time = 0.420 seconds for 1000 realizations of total = 50000
Error function = 3085.133
Change Log Ratio: 168.0 of 169.0 accepted (97.760% total)
Change Intensity: 337.0 of 507.0 accepted (66.706% total)
Change DF Gain: 77.0 of 98.0 accepted (78.815% total)
Change Baseline: 28.0 of 64.0 accepted (33.976% total)
Noise: 27.0 of 162.0 accepted (18.626% total)
Intervals: in microseconds, each from prev or zero time till new interval Interval1 96 Interval2 183 Interval3 7 Interval4 111 Interval5 21

**Pull request merged**
